/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { HanziStyle, PinyinStyle } from "./components/global";
export namespace Components {
    interface FontBg {
        "insertId": string;
        "styleConfig": HanziStyle;
        /**
          * 1 米字格 2 田字格
         */
        "type": number;
    }
    interface NbCard {
        "config": string;
        "word": string;
    }
    interface NbPinyin {
        "mediaList": Array<string>;
        "pinyinList": any;
        "styleConfig": PinyinStyle;
    }
}
declare global {
    interface HTMLFontBgElement extends Components.FontBg, HTMLStencilElement {
    }
    var HTMLFontBgElement: {
        prototype: HTMLFontBgElement;
        new (): HTMLFontBgElement;
    };
    interface HTMLNbCardElement extends Components.NbCard, HTMLStencilElement {
    }
    var HTMLNbCardElement: {
        prototype: HTMLNbCardElement;
        new (): HTMLNbCardElement;
    };
    interface HTMLNbPinyinElement extends Components.NbPinyin, HTMLStencilElement {
    }
    var HTMLNbPinyinElement: {
        prototype: HTMLNbPinyinElement;
        new (): HTMLNbPinyinElement;
    };
    interface HTMLElementTagNameMap {
        "font-bg": HTMLFontBgElement;
        "nb-card": HTMLNbCardElement;
        "nb-pinyin": HTMLNbPinyinElement;
    }
}
declare namespace LocalJSX {
    interface FontBg {
        "insertId"?: string;
        "styleConfig"?: HanziStyle;
        /**
          * 1 米字格 2 田字格
         */
        "type"?: number;
    }
    interface NbCard {
        "config"?: string;
        "word"?: string;
    }
    interface NbPinyin {
        "mediaList"?: Array<string>;
        "pinyinList"?: any;
        "styleConfig"?: PinyinStyle;
    }
    interface IntrinsicElements {
        "font-bg": FontBg;
        "nb-card": NbCard;
        "nb-pinyin": NbPinyin;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "font-bg": LocalJSX.FontBg & JSXBase.HTMLAttributes<HTMLFontBgElement>;
            "nb-card": LocalJSX.NbCard & JSXBase.HTMLAttributes<HTMLNbCardElement>;
            "nb-pinyin": LocalJSX.NbPinyin & JSXBase.HTMLAttributes<HTMLNbPinyinElement>;
        }
    }
}
