/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { HanziStyle, PinyinStyle } from "./components/global";
export namespace Components {
    interface FontBg {
        "insertId": string;
        "styleConfig": HanziStyle;
        /**
          * 1 米字格 2 田字格
         */
        "type": number;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface NbCard {
        "config": string;
        "name": string;
    }
    interface NbPinyin {
        "styleConfig": PinyinStyle;
    }
}
declare global {
    interface HTMLFontBgElement extends Components.FontBg, HTMLStencilElement {
    }
    var HTMLFontBgElement: {
        prototype: HTMLFontBgElement;
        new (): HTMLFontBgElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLNbCardElement extends Components.NbCard, HTMLStencilElement {
    }
    var HTMLNbCardElement: {
        prototype: HTMLNbCardElement;
        new (): HTMLNbCardElement;
    };
    interface HTMLNbPinyinElement extends Components.NbPinyin, HTMLStencilElement {
    }
    var HTMLNbPinyinElement: {
        prototype: HTMLNbPinyinElement;
        new (): HTMLNbPinyinElement;
    };
    interface HTMLElementTagNameMap {
        "font-bg": HTMLFontBgElement;
        "my-component": HTMLMyComponentElement;
        "nb-card": HTMLNbCardElement;
        "nb-pinyin": HTMLNbPinyinElement;
    }
}
declare namespace LocalJSX {
    interface FontBg {
        "insertId"?: string;
        "styleConfig"?: HanziStyle;
        /**
          * 1 米字格 2 田字格
         */
        "type"?: number;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface NbCard {
        "config"?: string;
        "name"?: string;
    }
    interface NbPinyin {
        "styleConfig"?: PinyinStyle;
    }
    interface IntrinsicElements {
        "font-bg": FontBg;
        "my-component": MyComponent;
        "nb-card": NbCard;
        "nb-pinyin": NbPinyin;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "font-bg": LocalJSX.FontBg & JSXBase.HTMLAttributes<HTMLFontBgElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "nb-card": LocalJSX.NbCard & JSXBase.HTMLAttributes<HTMLNbCardElement>;
            "nb-pinyin": LocalJSX.NbPinyin & JSXBase.HTMLAttributes<HTMLNbPinyinElement>;
        }
    }
}
